-- Smart Meter Readings System
-- Initial PostgreSQL schema for Supabase.
-- This migration creates structure only; it intentionally inserts no data.

BEGIN;

CREATE TABLE consumers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    consumer_code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(150) NOT NULL,
    email VARCHAR(255),
    phone VARCHAR(30),
    address TEXT,
    connection_type VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT consumers_connection_type_check
        CHECK (connection_type IN ('RESIDENTIAL', 'COMMERCIAL', 'INDUSTRIAL')),
    CONSTRAINT consumers_status_check
        CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

CREATE TABLE substations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    substation_code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(150) NOT NULL,
    location TEXT,
    capacity_kw NUMERIC(14, 3) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT substations_capacity_check CHECK (capacity_kw > 0),
    CONSTRAINT substations_status_check
        CHECK (status IN ('ACTIVE', 'INACTIVE', 'MAINTENANCE'))
);

CREATE TABLE feeders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    feeder_code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(150) NOT NULL,
    substation_id BIGINT NOT NULL,
    capacity_kw NUMERIC(14, 3) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT feeders_substation_fk
        FOREIGN KEY (substation_id) REFERENCES substations (id),
    CONSTRAINT feeders_capacity_check CHECK (capacity_kw > 0),
    CONSTRAINT feeders_status_check
        CHECK (status IN ('ACTIVE', 'INACTIVE', 'MAINTENANCE'))
);

CREATE TABLE meters (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meter_number VARCHAR(80) NOT NULL UNIQUE,
    consumer_id BIGINT NOT NULL,
    feeder_id BIGINT,
    meter_type VARCHAR(50) NOT NULL,
    installation_date DATE NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ONLINE',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT meters_consumer_fk
        FOREIGN KEY (consumer_id) REFERENCES consumers (id),
    CONSTRAINT meters_feeder_fk
        FOREIGN KEY (feeder_id) REFERENCES feeders (id),
    CONSTRAINT meters_id_consumer_unique UNIQUE (id, consumer_id),
    CONSTRAINT meters_status_check
        CHECK (status IN ('ONLINE', 'OFFLINE', 'MAINTENANCE'))
);

CREATE TABLE readings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meter_id BIGINT NOT NULL,
    reading_value NUMERIC(16, 3) NOT NULL,
    reading_timestamp TIMESTAMPTZ NOT NULL,
    source VARCHAR(20) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT readings_meter_fk
        FOREIGN KEY (meter_id) REFERENCES meters (id),
    CONSTRAINT readings_value_check CHECK (reading_value >= 0),
    CONSTRAINT readings_source_check
        CHECK (source IN ('SMART_METER', 'MANUAL', 'IMPORTED')),
    CONSTRAINT readings_meter_timestamp_unique UNIQUE (meter_id, reading_timestamp)
);

CREATE TABLE bills (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    consumer_id BIGINT NOT NULL,
    meter_id BIGINT NOT NULL,
    billing_period_start DATE NOT NULL,
    billing_period_end DATE NOT NULL,
    previous_reading NUMERIC(16, 3) NOT NULL,
    current_reading NUMERIC(16, 3) NOT NULL,
    units_consumed NUMERIC(16, 3) NOT NULL,
    energy_charge NUMERIC(14, 2) NOT NULL,
    other_charges NUMERIC(14, 2) NOT NULL DEFAULT 0,
    total_amount NUMERIC(14, 2) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    generated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT bills_consumer_fk
        FOREIGN KEY (consumer_id) REFERENCES consumers (id),
    CONSTRAINT bills_meter_fk
        FOREIGN KEY (meter_id) REFERENCES meters (id),
    CONSTRAINT bills_meter_consumer_fk
        FOREIGN KEY (meter_id, consumer_id) REFERENCES meters (id, consumer_id),
    CONSTRAINT bills_period_check CHECK (billing_period_start < billing_period_end),
    CONSTRAINT bills_previous_reading_check CHECK (previous_reading >= 0),
    CONSTRAINT bills_current_reading_check CHECK (current_reading >= previous_reading),
    CONSTRAINT bills_units_consumed_check CHECK (units_consumed >= 0),
    CONSTRAINT bills_energy_charge_check CHECK (energy_charge >= 0),
    CONSTRAINT bills_other_charges_check CHECK (other_charges >= 0),
    CONSTRAINT bills_total_amount_check CHECK (total_amount >= 0),
    CONSTRAINT bills_status_check
        CHECK (status IN ('DRAFT', 'GENERATED', 'PAID', 'OVERDUE')),
    CONSTRAINT bills_meter_period_unique
        UNIQUE (meter_id, billing_period_start, billing_period_end)
);

-- This table is a small topology projection for the supported grid edges.
-- Ownership remains authoritative in feeders.substation_id and meters.feeder_id.
CREATE TABLE grid_connections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    connection_type VARCHAR(30) NOT NULL,
    substation_id BIGINT,
    feeder_id BIGINT,
    meter_id BIGINT,
    connected_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    disconnected_at TIMESTAMPTZ,
    CONSTRAINT grid_connections_substation_fk
        FOREIGN KEY (substation_id) REFERENCES substations (id) ON DELETE CASCADE,
    CONSTRAINT grid_connections_feeder_fk
        FOREIGN KEY (feeder_id) REFERENCES feeders (id) ON DELETE CASCADE,
    CONSTRAINT grid_connections_meter_fk
        FOREIGN KEY (meter_id) REFERENCES meters (id) ON DELETE CASCADE,
    CONSTRAINT grid_connections_type_check
        CHECK (connection_type IN ('SUBSTATION_FEEDER', 'FEEDER_METER')),
    CONSTRAINT grid_connections_shape_check
        CHECK (
            (connection_type = 'SUBSTATION_FEEDER'
                AND substation_id IS NOT NULL
                AND feeder_id IS NOT NULL
                AND meter_id IS NULL)
            OR
            (connection_type = 'FEEDER_METER'
                AND substation_id IS NULL
                AND feeder_id IS NOT NULL
                AND meter_id IS NOT NULL)
        ),
    CONSTRAINT grid_connections_period_check
        CHECK (disconnected_at IS NULL OR disconnected_at > connected_at)
);

CREATE TABLE forecasts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    forecast_timestamp TIMESTAMPTZ NOT NULL,
    predicted_load NUMERIC(16, 3) NOT NULL,
    model_name VARCHAR(100) NOT NULL,
    meter_id BIGINT,
    feeder_id BIGINT,
    substation_id BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT forecasts_meter_fk
        FOREIGN KEY (meter_id) REFERENCES meters (id),
    CONSTRAINT forecasts_feeder_fk
        FOREIGN KEY (feeder_id) REFERENCES feeders (id),
    CONSTRAINT forecasts_substation_fk
        FOREIGN KEY (substation_id) REFERENCES substations (id),
    CONSTRAINT forecasts_predicted_load_check CHECK (predicted_load >= 0),
    CONSTRAINT forecasts_scope_check
        CHECK (num_nonnulls(meter_id, feeder_id, substation_id) <= 1)
);

CREATE TABLE alerts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type VARCHAR(20) NOT NULL,
    severity VARCHAR(20) NOT NULL,
    title VARCHAR(200) NOT NULL,
    description TEXT,
    related_entity_type VARCHAR(30),
    related_entity_id BIGINT,
    status VARCHAR(20) NOT NULL DEFAULT 'OPEN',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    resolved_at TIMESTAMPTZ,
    CONSTRAINT alerts_type_check
        CHECK (type IN ('CAPACITY', 'METER', 'CONSUMPTION', 'FORECAST', 'SYSTEM')),
    CONSTRAINT alerts_severity_check
        CHECK (severity IN ('INFO', 'WARNING', 'CRITICAL')),
    CONSTRAINT alerts_status_check
        CHECK (status IN ('OPEN', 'ACKNOWLEDGED', 'RESOLVED')),
    CONSTRAINT alerts_related_entity_type_check
        CHECK (
            related_entity_type IS NULL
            OR related_entity_type IN (
                'CONSUMER', 'METER', 'READING', 'BILL', 'SUBSTATION',
                'FEEDER', 'GRID_CONNECTION', 'FORECAST', 'SYSTEM'
            )
        ),
    CONSTRAINT alerts_related_entity_pair_check
        CHECK (
            (related_entity_type IS NULL AND related_entity_id IS NULL)
            OR (related_entity_type IS NOT NULL AND related_entity_id IS NOT NULL AND related_entity_id > 0)
        ),
    CONSTRAINT alerts_resolution_check
        CHECK (
            (status = 'RESOLVED' AND resolved_at IS NOT NULL)
            OR (status <> 'RESOLVED' AND resolved_at IS NULL)
        )
);

CREATE INDEX idx_feeders_substation_id ON feeders (substation_id);
CREATE INDEX idx_meters_consumer_id ON meters (consumer_id);
CREATE INDEX idx_meters_feeder_id ON meters (feeder_id);
CREATE INDEX idx_readings_meter_id ON readings (meter_id);
CREATE INDEX idx_readings_reading_timestamp ON readings (reading_timestamp);
CREATE INDEX idx_bills_consumer_id ON bills (consumer_id);
CREATE INDEX idx_bills_meter_id ON bills (meter_id);
CREATE INDEX idx_bills_billing_period ON bills (billing_period_start, billing_period_end);
CREATE INDEX idx_grid_connections_feeder_id ON grid_connections (feeder_id);
CREATE INDEX idx_grid_connections_meter_id ON grid_connections (meter_id);
CREATE UNIQUE INDEX idx_grid_connections_active_substation_feeder
    ON grid_connections (substation_id, feeder_id)
    WHERE connection_type = 'SUBSTATION_FEEDER' AND disconnected_at IS NULL;
CREATE UNIQUE INDEX idx_grid_connections_active_feeder_meter
    ON grid_connections (feeder_id, meter_id)
    WHERE connection_type = 'FEEDER_METER' AND disconnected_at IS NULL;
CREATE INDEX idx_forecasts_forecast_timestamp ON forecasts (forecast_timestamp);
CREATE INDEX idx_forecasts_meter_id ON forecasts (meter_id);
CREATE INDEX idx_forecasts_feeder_id ON forecasts (feeder_id);
CREATE INDEX idx_forecasts_substation_id ON forecasts (substation_id);
CREATE INDEX idx_alerts_status ON alerts (status);
CREATE INDEX idx_alerts_type_severity ON alerts (type, severity);
CREATE INDEX idx_alerts_related_entity ON alerts (related_entity_type, related_entity_id);

COMMIT;
